[2025-10-21T19:36:36.169+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-21T19:36:36.236+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airbnb_etl_pipeline.transform_airbnb_forsale manual__2025-10-21T19:20:31.904533+00:00 [queued]>
[2025-10-21T19:36:36.251+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airbnb_etl_pipeline.transform_airbnb_forsale manual__2025-10-21T19:20:31.904533+00:00 [queued]>
[2025-10-21T19:36:36.253+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-21T19:36:36.283+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_airbnb_forsale> on 2025-10-21 19:20:31.904533+00:00
[2025-10-21T19:36:36.296+0000] {standard_task_runner.py:63} INFO - Started process 373 to run task
[2025-10-21T19:36:36.327+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'airbnb_etl_pipeline', 'transform_airbnb_forsale', 'manual__2025-10-21T19:20:31.904533+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/airbnb_etl_dag.py', '--cfg-path', '/tmp/tmpjk5ig3dj']
[2025-10-21T19:36:36.340+0000] {standard_task_runner.py:91} INFO - Job 25: Subtask transform_airbnb_forsale
[2025-10-21T19:36:36.475+0000] {task_command.py:426} INFO - Running <TaskInstance: airbnb_etl_pipeline.transform_airbnb_forsale manual__2025-10-21T19:20:31.904533+00:00 [running]> on host abb000c1ba76
[2025-10-21T19:36:36.652+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='airbnb_etl_pipeline' AIRFLOW_CTX_TASK_ID='transform_airbnb_forsale' AIRFLOW_CTX_EXECUTION_DATE='2025-10-21T19:20:31.904533+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-21T19:20:31.904533+00:00'
[2025-10-21T19:36:36.655+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-21T19:36:36.681+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-21T19:36:36.683+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/scripts/etl_script.py", line 1215, in transform2
    airdna_data_for_sale = pd.json_normalize(all_properties)
                                             ^^^^^^^^^^^^^^
NameError: name 'all_properties' is not defined
[2025-10-21T19:36:36.736+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=airbnb_etl_pipeline, task_id=transform_airbnb_forsale, run_id=manual__2025-10-21T19:20:31.904533+00:00, execution_date=20251021T192031, start_date=20251021T193636, end_date=20251021T193636
[2025-10-21T19:36:36.778+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 25 for task transform_airbnb_forsale (name 'all_properties' is not defined; 373)
[2025-10-21T19:36:36.823+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-21T19:36:36.892+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-21T19:36:36.901+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
